version: '3.1'
services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: flask-server-demo
        container_name: flask-server-demo
        volumes:
            - ./:/app
        environment:
            - FLASK_APP=./app.py
        command: flask run --host=0.0.0.0
        #ports:
        #    - 8082:5000